### ISSUE TITLE
Deploy without node.js

### ISSUE THREAD

**Issue by derStephan** [dumbmatter/sas7bdat-web-viewer#1]
Hi,

i tried your sas7bdat web viewer on your website and would like to use it offline on my PC. But I don't understand what I need to download and what the resulting directory structure should be to get it running.

Can you give me some advice or make a complete package availabe for download, please? Thank you very much in advance.

**Comment by dumbmatter** [comment]
Install Node, npm, and Python 2, if you don't already have them.

Download this project. Run `npm install` and `npm build`. `npm install` is the only step that requires an Internet connection, and you just have to do it once on the initial install.

Then to run it, run `npm start` and go to the URL it shows.

**Comment by dumbmatter** [comment]
Alternatively, SAS has a free viewer you can download if you register on their website I think, that is probably better.

**Comment by derStephan** [comment]
Thanks for your reply. I kind of hoped that I run the resulting scripts locally without node.js. Running the universal viewer is the second choice I have of course but I really liked the idea of web based peeking into the data.

**Comment by dumbmatter** [comment]
It technically only needs Node.js for the build step, not for running. If you download the JS/CSS/HTML files used at http://dumbmatter.com/sas7bdat/ then you don't even need the build step.

**Comment by derStephan** [comment]
> It technically only needs Node.js for the build step, not for running.

Thats my point exactly.

>If you download the JS/CSS/HTML files used at http://dumbmatter.com/sas7bdat/ then you don't even need the build step.

I tried this but it is not working, probably I missed something. That was the reason for my question in the first place. I think your work would be easier to deploy, if you would just provide a zip-file with all files needed to run it offline. And you would have something to call "release" 
:-)

Regards
Stephan
